### ISSUE TITLE
Prevent "Former Tox Developer Created Malware To Hack Tox Users For The FBI"

### ISSUE THREAD

**Issue by verycrypt** [Tox/tox.chat#103]
https://news.slashdot.org/story/16/04/27/222233/former-tor-developer-created-malware-to-hack-tor-users-for-the-fbi

While Tox is not ToR, I want to know all people who actually writing the code.

> https://tox.chat/about.html
> Those listed without names have chosen to keep themselves anonymous (for now)

Anonymous is fine with me, buy why don't you just give us their @github username or something?
In short, can we actually trust these 'anonymous'?

**Comment by SkyzohKey** [comment]
I would ask about why are you creating so many shit issues that serve to nothing else to complain.

**Comment by Impyy** [comment]
What's up with the FUD title and the post on reddit about it? Clearly all you're trying to accomplish is scaring people away from Tox.

**Comment by SkyzohKey** [comment]
This is clearly unrelated to Tox. Why are you posting this on this repo? Do you really know what an issue is meant to? The bug tracker serves to **REPORT BUGS** or suggests **IMPROVEMENTS**, how this report/suggests something?

**Comment by aatestaa** [comment]
> post on reddit about it

This?

https://www.reddit.com/r/projecttox/comments/4gt46x/former_tox_developer_created_malware_to_hack_tox/

**Comment by Impyy** [comment]
Anyways, to answer your question:
> In short, can we actually trust these 'anonymous'?

No, you can't. But you shouldn't trust anyone who's public about their identity either. There's a reason why Tox is free software.

**Comment by aatestaa** [comment]
https://slashdot.org/submission/5812511/former-tox-developer-created-malware-to-hack-tox-users-for-the-fbi

**Comment by verycrypt** [comment]
...What the F. What's going on here?

> I would ask about why are you creating so many shit issues that serve to nothing else to complain.

@SkyzohKey I ask you to turn down your attitude.
I just post this for improvements; to explain people why Tox devs need to hide anonymous users.

Tell me, do you really think my other issues are shit? Because most of them are
bug reporting. You should say sorry to me I think.

> What's up with the FUD title and the post on reddit about it?

Huh? I didn't do it. I don't read reddit anyway.
Next time, try to offense the target DIRECTLY, why did you offend me, huh?

**Comment by verycrypt** [comment]
and @aatestaa, stop that.
end of discussion.

**Comment by aatestaa** [comment]
why closed?

**Comment by aatestaa** [comment]
Those listed without names have chosen to keep themselves anonymous
because
most of them are NSA! lol

**Comment by itsrachelfish** [comment]
hahahaahahahhaahahahhaahahahahahaah

y'all need to chill

please use bug reports for actual issues

thanks

**Comment by aatestaa** [comment]
forgot to link this
https://github.com/nylira/prism-break/issues/1521

**Comment by verycrypt** [comment]
Okay okay.

**Comment by aatestaa** [comment]
not okay. why closed!?
