### ISSUE TITLE
Need some details: Does Tox leak my IP address?

### ISSUE THREAD

**Issue by ghost** [Tox/tox.chat#109]
>    https://wiki.tox.chat/users/tox_over_tor_tot
>    "Does Tox leak my IP address?" section of https://wiki.tox.chat/users/faq

How will my 'friend'(also via Tor or non-tor) see my IP address(I'm via Tor).
127.0.0.1, 10.x.x.x(my local network IP), or Tor's exit node IP address?

**Comment by SkyzohKey** [comment]
Tox exit node IP.

**Comment by JFreegman** [comment]
Assuming you set your client to use TCP-only (as you always should when cloaking your IP address), your friend will see the IP address of the Tox TCP relay node that you're communicating through. That TCP node will see your Tor exit node.
