### ISSUE TITLE
Support category thing

### ISSUE THREAD

**Issue by ghost** [Tox/tox.chat#111]
before:
     Download
    About
    FAQ
    Clients
    Wiki
    Mailing lists
    Blog

after:
     Download
    About
    FAQ
    Clients
    Wiki
    Blog

1. Move 'Mailing lists' link to Wiki.
2. Add 'IRC' link to Wiki.

because:
Both mailing lists and IRC belongs to 'support' category.
Adding a 'Support' category, or moving them to 'FAQ' or 'Wiki' is a good idea I think.

Also, I find it hard to find your IRC.
https://github.com/irungentoo/toxcore/issues/1596#issuecomment-230147826

**Comment by nurupo** [comment]
>Move 'Mailing lists' link to Wiki.
>Add 'IRC' link to Wiki.

Wiki already has IRC, it's in the navigation menu on the left of any wiki page. Actually, it links to https://wiki.tox.chat/users/community#irc, which also has mailing lists, twitter and reddit. I guess you want the IRC link to also be mentioned on the main page of the wiki?
