### ISSUE TITLE
library versioning and official releases

### ISSUE THREAD

**Issue by felix-salfelder** [Tox/tox.chat#116]
(looking for a packageable tox library to get into a major GNU/linux distribution, but it seems that i am not the only one)

i came here, because you are in charge of the tox.chat domain, and you provide several other downloads related to the tox project on a site under that domain. there's a lot of development taking place at random places and subject to random practices. it's very hard to do serious packaging based on that.

let me suggest to provide an official tox tarball with a version number on it containing consistently versioned libraries. any random version that you chose, will definitely do for a start. future tarballs must increase relevant version numbers, according to how the code has changed.

some background: the tox package (sometimes "toxcore") contains everything you need to ship proper release tarballs. it has a package version triplet and contains two libtool versioned libraries. all version triplets i could find are currently/still stuck at 0.0.0. type `make dist` to create this tarball (after configuring, after choosing a development repository).

version numbers are quite common for libraries to let linkers and binaries select the libraries with the desired or compatible interface. the original tox developer chose the libtool versioning scheme, likely because (s)he knew the implications, and because it works very well for a plethora of other libraries.
see [this link](http://ftp.gnu.org/old-gnu/Manuals/libtool-1.4.2/html_node/libtool_34.html) for the full story or just read the relevant comment in the `configure.ac` file, if you are a tox developer.

**Comment by ng-0** [comment]
I can add to this that it is preferable as a packager to have 1 file per version with 1 static hashsum than to have 1 file which just follows HEAD/master with a changing hashsum.

At least the Nix, Guix, and Gentoo build systems require sums to be existant, for Guix I currently package "repo at commit number with calculated sum of $sum" where for Gentoo it is just "repo at commit number".
For a application/protocol which aims to be secure it should be a goal to have also secure, verifable releases.

**Comment by SkyzohKey** [comment]
@GrayHatter @nurupo @Impyy @iphydf, related to https://github.com/TokTok/toxcore/pull/56

**Comment by GrayHatter** [comment]
> For a application/protocol which aims to be secure it should be a goal to have also secure, verifiable releases.

Really, why? I mean to ask, why would that be better than git releases? From a security standpoint.

**Comment by GrayHatter** [comment]
> The original tox developer chose the libtool versioning scheme, likely because (s)he knew the implications, and because it works very well for a plethora of other libraries.

Actually, irungentoo selected semver for the versioning system after it was selected and insisted upon by the community.

**Comment by felix-salfelder** [comment]
GrayHatter, semver is perfectly fine. but semver is for the *package version*. probably date would be simpler, easier to understand and thus better suited. i dont care too much, and i'm fine with anything you are planning to do. please note that package versions are mostly unrelated to my request.

libraries need a versioning suited for library interfaces. and it's already there, well chosen and implemented by the author, whatever the community has "selected" and "insisted" afterwards. the version just needs to be incremented accordingly, and that's not a hard thing to do. anyone can still easily ignore the versions, if (s)he decides so (but clearly not the other way round).

going further: it seems it make sense to build `tox-0.0.0.tar.gz` from commit [755f084e8720](https://github.com/irungentoo/toxcore/commit/755f084e8720b349026c85afbad58954cb7ff1d4). i strongly recommend to make this tarball available somewhere at https://tox.chat. incrementing the library interface version will be necessary for the subsequent releases.

**Comment by nurupo** [comment]
Tox clients and libraries are developed independently by different groups of developers, so if you want a client or a library to do versioning, then please open an issue on their respected issue tracker. This is an issue tracker for the tox.chat website, which just links to products of these groups of developers.

**Comment by nurupo** [comment]
>i strongly recommend to make this tarball available somewhere at https://tox.chat.

Once toxcore releases a tarball, it will be possible for us to provide it on the website, with the signatures and checksums provided by the toxcore developers, but since toxcore hasn't done any releases, there is nothing we can do. Just picking a commit out of a repository and calling it a release and publishing it on the website, despite the library developers making a release, is a quite big lie and kick in the balls for library the developers -- why would we do that?

>incrementing the library interface version will be necessary for the subsequent releases.

The library developers would need to do the incrementing, not the people managing the website.

**Comment by felix-salfelder** [comment]
thanks nurupo, possibly you are right and not entitled to decide about what to call a release.

> Once toxcore releases a tarball

i don't know who 'toxcore' is, which is one of the reasons i was asking here. i'm looking forward to suggestions.

**Comment by SkyzohKey** [comment]
>i don't know who 'toxcore' is,

ToxCore is the core of Tox, that's not a person but the Tox API (for explaining that simply)
