### ISSUE TITLE
there is no qtox-unity

### ISSUE THREAD

**Issue by ZamanOof** [Tox/tox.chat#118]
after follow instruction from
https://tox.chat/download.html#gnulinux
in the last step to install qtox-unity
but there is no qtox-unity package and try this command to show unity package
cat /var/lib/apt/lists/pkg.tox.chat* | grep "unity"
there was't unity package .

**Comment by nurupo** [comment]
Thanks for pointing this out. `qtox-unity` is [available](https://pkg.tox.chat/debian/dists/nightly/release/binary-amd64/Packages) only for `release` codename (e.g. `deb https://pkg.tox.chat/debian nightly release`). However, the `release` codename contains static binaries and is deprecated, so the download instructions need to be updated.

**Comment by nurupo** [comment]
Closing because the instructions should be a little bit less confusing now that #122 has merged.
