### ISSUE TITLE
Request - A shortcut "Press to talk" or "enable/disable" microphone

### ISSUE THREAD

**Issue by PepinLeBref** [Tox/tox.chat#123]
Would be nice to have an option to configure/create a shortcut to enable/disable the microphone.
Thanks guys :-D

<3 Tox

**Comment by ProMcTagonist** [comment]
Hi! Thanks for reaching out to us! This repo is actually just for the Tox website.

Tox is separated into a core, and many clients, which all use the core. Your feature request falls into the domain of clients, so you should recreate this issue on the repo for the client you wish to see implement the feature.

The most popular clients are qTox and uTox, so you probably want to open your issue on the [qTox issue tracker](https://github.com/qtox/qtox) or the [uTox issue tracker](https://github.com/utox/utox).

**Comment by PepinLeBref** [comment]
Thanks for your reply, sorry I'm in the wrong place ^^
