### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by gbaumgart** [Tox/tox.chat#126]
Hi,
i am having a hard time to find the actual source. Do you know where it is ? 

i found only dozens of clients but not the actual server,...

thanks a lot.

**Comment by anoadragon453** [comment]
Tox is a peer-to-peer protocol and thus does not have any server component - it is client side only. 

If instead you are searching for the code run on the tox.chat server well then you're looking at it. 

On October 4, 2016 3:49:16 PM PDT, gbaumgart <notifications@github.com> wrote:
>Hi,
>i am having a hard time to find the actual source. Do you know where it
>is ? 
>
>i found only dozens of clients but not the actual server,...
>
>thanks a lot.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Tox/tox.chat/issues/126

-- 
Sent from my K-9/p≡p on Android.

**Comment by gbaumgart** [comment]
ah, vale, thanks!
