### ISSUE TITLE
can't find the link to the tox core git repo

### ISSUE THREAD

**Issue by shalnoff** [Tox/tox.chat#130]
I spent about 30 minutes to find the link to the tox core git repo. And still not pretty sure that this is an official one. It would be great (and obvious) to add this link to the Download section of the website. 

Thank you for great IM software :)

**Comment by nurupo** [comment]
Yes, you are right, it would be nice if the the Download page listed toxcore library and even possibly other development related downloads. Currently the toxcore repo is linked in the footer of the website under the GitHub icon, which I realize is not very obvious.

Unfortunately we currently don't have anyone actively maintaining the website who could add a section to the Download page like that, our previous maintainer left several months ago and now I'm trying to maintain the website by fixing small parts I can fix without going too deep into html and web stuff. So as much as I'd like it to be added, don't expect it to be done anytime soon.

**Comment by robinlinden** [comment]
I could add a section like that. Want me to do a PR or want to come up with a nicer design for the icon or more links or something?

![toxchat2](https://cloud.githubusercontent.com/assets/8304462/19521918/bc9b03b6-9615-11e6-9730-37273a8b7f2d.png)
![toxchat1](https://cloud.githubusercontent.com/assets/8304462/19521917/bc9b058c-9615-11e6-91cb-fa01c660bc97.png)
