### ISSUE TITLE
Remove Gentoo and Arch download options

### ISSUE THREAD

**Issue by nurupo** [Tox/tox.chat#149]
Our Gentoo overlay and Arch repository are not maintained by anyone, so it might make sense to just remove them from the website as to not confuse users. Currently the Download page says that they are not maintained, meaning "they may work but if they don't — you are on your own", but we keep getting user complains about them, so it might be better to just remove them. Having a not maintained repo listed on the website, explicitly saying "it's not maintained", is kind of confusing in itself.

**Comment by emdee-is** [comment]
Tox and qtox are already in gentoo so please remove the old gentoo overlay.

**Comment by nurupo** [comment]
Removed in #196.
