### ISSUE TITLE
uTox Audio Issue

### ISSUE THREAD

**Issue by jcotman** [Tox/tox.chat#151]
I am not sure if this should be here, but the website where I downloaded uTox suggested to post issues here.

I am having trouble with the audio in uTox standalone, Debian Testing, Intel audio.

The issue(s) is:

1 - The other use cannot hear me.
2 - I cannot hear the other user
3 - EXCEPT when I go to Settings --> Audio and Video --> Preview and click the phone icon.

In this case, the phone icon turns red and I hear the other user very choppily.  It's possible that he could do the same with me.  Unknown.

What information can I provide to make this report more useful?

Thank you.  And thank you for tox.  I'm looking forward to using it.

**Comment by nurupo** [comment]
This is repository for the tox.chat website. Please file issue to the uTox client repository https://github.com/uTox/uTox.

**Comment by jcotman** [comment]
Oops.  Thank you.
