### ISSUE TITLE
trifa client

### ISSUE THREAD

**Issue by Daniel-at-github** [Tox/tox.chat#163]
You could add [Tox Reference Implementation for Android [TRIfA]](https://github.com/zoff99/ToxAndroidRefImpl) to the client list.
[Installable from f-droid](https://f-droid.org/repository/browse/?fdid=com.zoffcc.applications.trifa).

**Comment by nurupo** [comment]
https://github.com/tox/tox.chat#i-want-my-client-to-be-listed-on-your-website

**Comment by zoff99** [comment]
no it is not

**Comment by Daniel-at-github** [comment]
I commented it in case it were useful.
May be they be compliant with TCS in the future, but I will close the issue.

**Comment by zoff99** [comment]
@Daniel-at-github do you use TRIfA yourself?

**Comment by Daniel-at-github** [comment]
Nope, just see it as new in F-droid and trying to pass the news.
