### ISSUE TITLE
Improve qTox client description

### ISSUE THREAD

**Issue by tox-user** [Tox/tox.chat#172]
In here https://tox.chat/clients.html qTox's description just says:
> A Qt graphical user interface for Tox.

Really, is that all you are gonna say? It does a poor job at convincing people to try this software and it provides no new information (the table already tells us it uses Qt). What are the advantages of this client? What are the project's goals? Look at descriptions of other clients on that page and how much better they are! We need to sum up all the good things about qTox and write a new description.

**Comment by nurupo** [comment]
@sudden6 @Diadlo want to write a description for qTox?

**Comment by sudden6** [comment]
Proposal:

```
qTox is a powerful client based on Qt, it has a pretty and feature rich user interface as well as a fast core written in C++. qTox runs on Windows, Linux, MacOS and FreeBSD with text message, audio, video and file transfer support. Additionally it has support for Identicons as avatars as well as text and audio group chats. New features are regularly added by our active and welcoming community.
```

Can any native english speaker please review that? :)

**Comment by tox-user** [comment]
Sounds good! I'm not sure if it's worth to mention identicons. Won't they become a standard for all clients soon? They are a cool feature, but most people probably won't care about it (until they become familiar with it) and many might not even know what they are.

Maybe I would change one sentence a bit:
```
qTox runs on Windows, Linux, MacOS and FreeBSD and offers text messaging, audio and video calls, screen sharing and file transfer.
```

**Comment by anthonybilinski** [comment]
My suggested changes:
1. In the first sentence, the comma separates two distinct ideas. You can change “, it has” with ”, with” to connect the two ideas. Alternatively change comma to a period and keep the “it”.
2. “Pretty” feels like a strange adjective for UI, I think “intuitive” or “sleek” would work better.
3. Maybe switch order of “group text/audio” with Identicons. Groups seem more important and central to the program.
4. For "message, audio, video and file transfer" adding a comma between "video" and "and" clearly separates video from file transfers.

With my suggested changes:

qTox is a powerful client based on Qt, with an intuitive and feature rich user interface as well as a fast core written in C++. qTox runs on Windows, Linux, MacOS and FreeBSD with text message, audio, video, and file transfer support. Additionally it has support for text and audio group chats as well as Identicons as avatars. New features are regularly added by our active and welcoming community.

**Comment by sudden6** [comment]
Ok, I like both changes, so i merged them together:

qTox is a powerful client based on Qt, with an intuitive and feature rich user interface as well as a fast core written in C++. qTox runs on Windows, Linux, MacOS and FreeBSD and offers text messagging, audio and video calls, screen sharing and file transfers. Additionally it has support for text and audio group chats as well as Identicons as avatars. New features are regularly added by our active and welcoming community.

**Comment by nurupo** [comment]
Made a pull request with the latest text from sudden6.

**Comment by nurupo** [comment]
@sudden6 btw, feel free to open your own PR if you want the commit to be authored by you, I would close my PR in that case.

**Comment by sudden6** [comment]
@nurupo np, thanks for reminding me and opening the PR :)
