### ISSUE TITLE
Webcam OSX

### ISSUE THREAD

**Issue by ricardolmsilva** [Tox/tox.chat#182]
Hi, im using qTox v1.13.0 on OSX Sierra and the Webcam in qTox is not detect as you can see in the screenshot below.

![screen shot 2017-12-14 at 06 51 34](https://user-images.githubusercontent.com/34528668/33979210-3c79ae7c-e09b-11e7-98e2-7db73e4093ed.png)

Can i do something to fix that inssue?
Thank you!

**Comment by tox-user** [comment]
This repository is for the website only. You should post your issue in https://github.com/qtox/qtox

**Comment by sudden6** [comment]
This can be closed as the problem was fixed in https://github.com/qTox/qTox/issues/4866
