### ISSUE TITLE
konv.im website is dead

### ISSUE THREAD

**Issue by tox-user** [Tox/tox.chat#202]
The link to konv.im should be removed from https://tox.chat/clients.html.

**Comment by SkyzohKey** [comment]
As the konv.im / Ricin owner, I agree that the link should be replaced by the GitHub repository as the client is still functional ;)

**Comment by nurupo** [comment]
Fixed in https://github.com/Tox/tox.chat/commit/373017723e7c91cbbf4cad55e001996c76e96a38.
