### ISSUE TITLE
F-Droid repository bad signature

### ISSUE THREAD

**Issue by radiocane** [Tox/tox.chat#204]
F-Droid complains with "Repository was not signed correctly: The supplied certificate fingerprint does not match!"
I tried with the https sha256 fingerprint
06:ED:67:F7:51:D4:B6:ED:20:13:C1:FC:0B:1F:66:DC:CC:03:86:E7:CA:82:15:D0:54:98:FB:6B:9D:CB:F7:81
and F-Droid shows the same message.
What's wrong?

**Comment by nurupo** [comment]
You are using the wrong fingerprint. Here is the fingerprint of the certificate used to sing our F-Droid repository https://tox.chat/download.html#fdroid.

**Comment by nurupo** [comment]
Could you check again using the fingerprint from the website? It should be fixed now.

What happened was that Java got updated and the keytool program, which is part of Java, started adding

```
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore ./keystore.jks -destkeystore ./keystore.jks -deststoretype pkcs12".
```

at the end of every keytool invocation. F-droid python script, the official one, which we use to manage the repository, uses the output of the keytool program to sign the repository and that warning message was messing everything up, being appended to the end of the public key, signature and whatnot.

**Comment by radiocane** [comment]
it's working, thanks :)
