### ISSUE TITLE
not excepting toxme.io

### ISSUE THREAD

**Issue by 2635599** [Tox/tox.chat#210]
just removed and added qtox back and when i go to register on the serber i get told that it does not support toxme. i' at a loss help.

**Comment by nurupo** [comment]
Sorry, I have no idea about qTox and toxme. You might have better luck asking on [qTox's issue tracker](https://github.com/qtox/qtox/issues) rather than the issue tracker for tox.chat website.

**Comment by 2635599** [comment]
thanks just created ticket there.
