### ISSUE TITLE
Why isn't TRIfA mentioned in the client list?

### ISSUE THREAD

**Issue by thomas725** [Tox/tox.chat#235]
[TRIfA](https://f-droid.org/en/packages/com.zoffcc.applications.trifa/) seems to me to be by far the most stable and feature rich Android Tox client, though on https://tox.chat/clients.html only aTox is mentioned, why is that?

Would you accept a pull request to https://github.com/Tox/tox.chat/blob/master/themes/website/templates/clients.html to remedy that mistake?

**Comment by nurupo** [comment]
TRIfA uses [a weird-looking fork of Toxcore](https://github.com/zoff99/c-toxcore) which, as far as I know, no core developers have reviewed or looked at at all. [GitHub says](https://github.com/zoff99/c-toxcore) that it's 903 commits ahead of [TokTok/c-toxcore](https://github.com/TokTok/c-toxcore). It's developed by TRIfA's developer alone while core developers continue working on TokTok/c-toxcore (even if it's not very active right now). As such, it's not something we are comfortable recommending users to use.

**Comment by thomas725** [comment]
It still seems mostly compatible with all the other Tox-Clients I tried...

Could you specify what's "weird-looking" about it? Sorry, I'm not really too fluent in the C / C++ language...

Isn't Tox about the specification instead of one specific library implementation of it? Seems a bit arbitrary that all client's need to use the same specific implementation of the Tox protocol?

You could maybe put a warning sign next to it saying you cannot judge if and how safe it still is with it's toxcore modifications - instead of leaving it out all together?

**Comment by nurupo** [comment]
Again, the issue is that it uses a fork of Toxcore that haven't been reviewed by any core developer, or anyone else for that matter. As such, it's not something we are comfortable recommending users to use.

Also, to quote the README:

>When submitting a request for client addition [to the website], keep in mind that we expect the clients we list to be of high quality. It's not our intention [for the website] to list every single Tox client in existence. Rather, the intention is to provide a curated list of Tox clients.

>If you don't think that your client is ready to be listed on the website but still want to list it somewhere, you could add it to the list of clients on the [wiki](https://wiki.tox.chat/clients) and the [TokTok website](https://toktok.ltd/integrations.html)([repo](https://github.com/TokTok/website)).

The tox.chat website features a curated list of clients, while the wiki and the TokTok websites are mostly unrestricted. To note, TRIfA is, in fact, listed on both of the wiki and the TokTok website.
