### ISSUE TITLE
Checkout Tinode

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [Tox/tox.chat#237]
Tox and Tinode are very interesting and valuable projects. I feel they both can benefit from cross collaboration, support and a potential merger. Dev bandwidth can be pooled and both projects sped up. The server can have two modes - distributed open to public and distributed private personal use server mode. If both clients are trying to solve similar problems, why not merge efforts.

Disclaimer: I am not part of Tinode or Tox. Just someone who is looking for a chat server and chat client for his app's requirement. I found tox and tinode as good options. They all solve some parts of the problem. I see tinode stretched thin. Don't know about Tox's dev resource situation. If the two merge and work together, they will solve the problem they have set out to achieve faster

**Comment by nurupo** [comment]
Thank you for reaching out. Don't think we are interested in collaborating as the projects are rather different, with different goals and design architectures, e.g. federated vs p2p distributed. Tox developers are not interested in a federated solution.
