### ISSUE TITLE
Digitalocean Mirror for testing

### ISSUE THREAD

**Issue by Programmer1603** [Tox/tox.chat#247]
Hello,
I want to develop some additional features and host them myself before creating a pullrequest in order to see if i get it to work properly. Therefore i tried to host a mirror on digital ocean so i can test the "test-webpage" with some friends of mine, but i am unable to run it as app.... Could somebody possibly help me to host a mirror of this website on digitalocean for testing purposes? If so thank you in advance. If you link your github you get free credit, so dont be afraid to help.
~sincerely Programmer1603

**Comment by robinlinden** [comment]
Hi!
You can run `make devserver_start` in the folder you cloned tox.chat to you'll start a local server you can use while testing your edits. No need to pay for hosting when messing around locally. :P You can see instructions here: https://github.com/Tox/tox.chat#usage

**Comment by Programmer1603** [comment]
Oh thank you, but digitalocean is free... and i wanted to test it with friends, i already tested it locally and its amazing!
Thank you for your amazing work!!
