### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by Zer0-One** [Tox/tox.chat#29]
The site needs an "About" page that explains what the Tox Project is, who runs it, etc.

Don't worry about filling in the text, just come up with the layout and styles. I'll take care of the rest.

**Comment by installgen2** [comment]
What sort of content do you want to put there? How should I make the layout?

**Comment by anoadragon453** [comment]
Brief summary of the project, and an explanation of toxcore vs. clients might be a good start. How it's community driven, free from spying, yadda yadda.

This is probably a good place to source info from: https://wiki.tox.chat/users/faq#what_is_tox
