### ISSUE TITLE
List of packages

### ISSUE THREAD

**Issue by Zer0-One** [Tox/tox.chat#39]
It's difficult for a user to know which packages they're able to install from the repositories if we don't point them in the right direction. We should compile a list of clients and other utilities that a user can install from our repos.

**Comment by installgen2** [comment]
@Zer0-One

> To see all available clients, do:
> ```cat /var/lib/apt/lists/pkg.tox.chat* | grep "Package: "```

**Comment by Zer0-One** [comment]
think of something more user-friendly.

**Comment by installgen2** [comment]
@Zer0-One how is it not user friendly? it's a command you can simply copy-paste, which will give you a full and 100% up to date list of packages

**Comment by ProMcTagonist** [comment]
Maybe we should switch to PHP and install the apt repo on the server, and have an exec populate the popup :}

**Comment by installgen2** [comment]
@ProMcTagonist p- p-pls no ;_;

**Comment by ProMcTagonist** [comment]
No, it would be bad to allow remote exec on the webserver. We'll set up a separate backend server with the apt repo and a listening PHP file to do the exec, and we'll just xhr to it, so the front end is all secure :}

**Comment by installgen2** [comment]
no backend pls no I can't do it PLS

**Comment by anoadragon453** [comment]
Pretty sure this whole thing is low priority anyways considering we have a command to access it and a user-friendly download page for the most recent packages.

**Comment by installgen2** [comment]
@anoadragon453 :+1: :+1: :+1: :eggplant:

**Comment by optimumtact** [comment]
it would take about 30 seconds to write something that runs that command and pipes it into a html file to serve

**Comment by installgen2** [comment]
@optimumtact I can include it in the (soon to be added) "build" script, which will run the website through the translations engine and maybe other stuff, but it really just seems stupid and silly smh.

**Comment by ProMcTagonist** [comment]
don't make me /s things

**Comment by installgen2** [comment]
We have a clients page now as requested @Zer0-One
