### ISSUE TITLE
Some users unable to see navbar text

### ISSUE THREAD

**Issue by benwaffle** [Tox/tox.chat#40]
![screenshot from 2015-12-26 14-27-17](https://cloud.githubusercontent.com/assets/1713819/12008143/c9a62cc6-abdc-11e5-875d-b25720e2039f.png)

I think it's related to the font Fira Sans

**Comment by ProMcTagonist** [comment]
What version of Firefox are you using? 

What addons?

What OS?

**Comment by benwaffle** [comment]
Linux, Firefox Developer Edition and Firefox beta, ublock origin is probably the one that matters

**Comment by ProMcTagonist** [comment]
Does it work for you in other browsers? With addons disabled? I can't duplicate your problem so you've got to do some testing on your system so we can isolate the problem.

**Comment by installgen2** [comment]
Issue is entirely unrelated to Firefox, as has been very tested already.

**Comment by installgen2** [comment]
@benwaffle is this only the navbar text? or does it affect other parts of the page too

**Comment by benwaffle** [comment]
I can't see "A New Kind of Instant Messaging", or the titles for the 2x3 grid of features, or "What makes Tox different?" or the creative commons license text

![screen shot 2015-12-27 at 18 12 56](https://cloud.githubusercontent.com/assets/1713819/12013152/a5fc854c-acc5-11e5-9fe3-0e97ba54ed79.png)

**Comment by ProMcTagonist** [comment]
bad font weight?

**Comment by benwaffle** [comment]
yup, `font-weight: 300` is invisible (200 and 400 are fine though)
