### ISSUE TITLE
Debian option shows no indication of also being for Ubuntu

### ISSUE THREAD

**Issue by installgen2** [Tox/tox.chat#42]
Lots of Ubuntu users will not be aware that the Debian packages will be compatible. Perhaps we can have the Ubuntu logo beside the debian one? @ProMcTagonist

**Comment by ProMcTagonist** [comment]
Hey, you're back. I'll post some ideas.

**Comment by ProMcTagonist** [comment]
Ehhgh
![debuntu cut](https://cloud.githubusercontent.com/assets/4358079/12011967/bc20b072-ac99-11e5-8953-0b7863a2d1d0.png)

![debuntuboth](https://cloud.githubusercontent.com/assets/4358079/12011984/8fe58c84-ac9a-11e5-8c49-11b74f9478d7.png)

**Comment by installgen2** [comment]
The top image looks a whole lot cooler, but a bit broken, maybe it would look better with Ubuntu in the bottom left?

**Comment by ProMcTagonist** [comment]
Ehhhhhh

![debuntu combo 3](https://cloud.githubusercontent.com/assets/4358079/12018289/b416839e-ad15-11e5-91c5-007c31a556b0.png)

**Comment by installgen2** [comment]
ummmm... yeah ok maybe not

Could the debian logo in the 1st picture be resized so it aligns with Ubuntu? Otherwise lets just go with the second one.

**Comment by ovalseven8** [comment]
Why not just an extra logo for Ubuntu? Would look better and is clearer.

**Comment by installgen2** [comment]
But it would be exactly the same contents as Debian, that would just be silly.

**Comment by RowenStipe** [comment]
![](http://i.imgur.com/18UWfX4.png)

Was this the kinda image you where going for?

**Comment by Zer0-One** [comment]
can we please stop mashing up the debian and ubuntu logos? they all look equally terrible, and will be equally confusing to an end-user. kthxbai

**Comment by installgen2** [comment]
@RowenStipe the alignment is all good but I think the long part of the debian logo is important

@Zer0-One I'm having an artistic breakthrough here do not disturb me

**Comment by RowenStipe** [comment]
@installgen2 I've tried repositioning the logos and have come to the conclusion that it would be too cluttered to try and fit the "leg" of the Debain logo with Ubuntu's logo and it ends up as @Zer0-One one says. Terrible.

I did decide to edit the previous one a bit to make the Debain logo more prominent, but it could be confusing to an end user if they are presented with just a logo. It might be an idea to simply add text below the Linux icons on the downloads page to avoid it.
Something like: `Debain/Ubuntu    Gentoo     Arch` basically.

Below is the modified logo

![debuntu](https://cloud.githubusercontent.com/assets/1356364/12307721/13ae1afa-ba0f-11e5-8caa-dac055b83156.png)

**Comment by ProMcTagonist** [comment]
Honestly if we're not gonna show both in full we should just put the ubuntu logo because Debian people will understand and we're used to clicking on ubuntu logos and rolling our eyes

**Comment by Zer0-One** [comment]
@ProMcTagonist no, the other way around. if we do stick with a single logo, it should be the debian logo, given that ubuntu is a debian derivative.

**Comment by RowenStipe** [comment]
I agree with @Zer0-One, Debain logo should be used if you do go with a single logo. And again, I say labels should be added below just to help even the most basic of Linux noobs.

**Comment by ProMcTagonist** [comment]
@Zer0-One my concern was Ubuntu users not knowing that and not knowing to click Debian

@RowenStipe Good idea, then we can just put "Debian/Ubuntu" under it and everything's solved :)

**Comment by anoadragon453** [comment]
Just have an Ubuntu Logo, but put "Debian/Ubuntu" under it, and stick "Arch" and "Gentoo" under the other images to keep it consistent.
