### ISSUE TITLE
Terrible mobile website

### ISSUE THREAD

**Issue by DaaOtt** [Tox/tox.chat#45]
![The fuck is this?!](http://i.imgur.com/Hqh40JF.jpg)

Please just disable it.

**Comment by Zer0-One** [comment]
1. This is the wrong repository for your issue
2. Work has ceased on our production site, and we're focusing on this one in order to replace it

**Comment by installgen2** [comment]
\>flight mode icon
\>9:10

You had a potential to be ebin and threw it away, I am disappointed in you @DaaOtt

Also, mobile website looks fine fam

![https://sr.ht/mIws.png](https://sr.ht/mIws.png)
![https://sr.ht/RITd.png](https://sr.ht/RITd.png)
![https://sr.ht/WbFz.png](https://sr.ht/WbFz.png)
