### ISSUE TITLE
Clients Page improvements

### ISSUE THREAD

**Issue by Zer0-One** [Tox/tox.chat#47]
- [x] The Clients page should have galleries of screenshots for users to look at. You can save space by using lightbox or something like that. 

- [x] Every section should include a small table to the right of the screenshot listing the same information as can be found on the wiki (repo url, maintainer, language, etc.).

**Comment by SkyzohKey** [comment]
If you code something like lightbox please do it using CSS3-only. No need for JavaScript to do this. It can easily be acheived without JS and it's better cuz' this would improve page load time.

**Comment by Zer0-One** [comment]
@SkyzohKey did you wanna whip something up for us?

**Comment by SkyzohKey** [comment]
I'm really busy in real life, I only respond via GitSkarios (awesome app) on my mobile phone. Can't code for at least 2 weeks, but you can follow this nice tutorial/sample: http://www.designcouch.com/home/why/2013/11/01/responsive-css3-lightbox-with-no-javascript/
