### ISSUE TITLE
Alternate page listing

### ISSUE THREAD

**Issue by Zer0-One** [Tox/tox.chat#48]
In addition to the nav-bar at the top right of every page, we should have a separate navigation bar listing pages on the actual site. The FAQ, About, and Client pages should all be reachable within one click from the index page.

**Comment by benwaffle** [comment]
>In addition to the nav-bar at the top right of every page, we should have a separate navigation bar 

bad idea

**Comment by Zer0-One** [comment]
@benwaffle would you like to enlighten us regarding better ways of doing this?

**Comment by installgen2** [comment]
@Zer0-One move all external links to footer and use navbar for pages?

**Comment by benwaffle** [comment]
have a single navbar, and move Code, Mailing Lists, and IRC to a new developer.html page

**Comment by benwaffle** [comment]
@installgen2 nobody will find things in the footer

**Comment by installgen2** [comment]
@benwaffle and they won't find you in my basement either, so shut up and make this developer page

**Comment by Zer0-One** [comment]
I disagree with both of you. Both of those suggestions hides the links too much. All of those links should be reachable from the index page.

**Comment by installgen2** [comment]
@Zer0-One we could replace all the external link buttons with trashcans to make room in the navbar

**Comment by nurupo** [comment]
@installgen2 you somehow missed the about.html and now it has different footer than all other pages (maybe something else different too?).
