### ISSUE TITLE
bylaws.pdf is missing

### ISSUE THREAD

**Issue by codedust** [Tox/tox.chat#49]
The link to the pdf in `about.html` is death. This should be fixed before the site goes live...

**Comment by Zer0-One** [comment]
The link is dead on purpose. The bylaws aren't yet complete. I'll remove the section until they are.

**Comment by codedust** [comment]
Thanks for the clarification. Are there currently any concrete plans to establish the `Tox Project` as a legal intituition?

**Comment by Zer0-One** [comment]
@codedust , yes, and if you want to hear more about it, please ping me on IRC. This isn't the place to discuss that.

**Comment by codedust** [comment]
Yep. You are right. Thanks!

**Comment by codedust** [comment]
The link to the PDF still exists: https://tox.chat/about.html
