### ISSUE TITLE
tox.chat/bylaws.pdf does not exist

### ISSUE THREAD

**Issue by anoadragon453** [Tox/tox.chat#53]
>If you'd like to learn, in more detail, about what the Tox Project is, and how it's being run, see [The Tox Project Organizational Bylaws](https://tox.chat/bylaws.pdf).

Link is dead.

**Comment by Zer0-One** [comment]
@anoadragon453  https://github.com/Tox/tox.chat/issues/49

**Comment by anoadragon453** [comment]
Ah, silly me. Thanks.

**Comment by hjek** [comment]
Still doesn't exist.

**Comment by Zer0-One** [comment]
@hjek and it never will.

# F

**Comment by hjek** [comment]
It is still being linked to in the bottom of `https://wiki.tox.chat/about/the_tox_project`.

**Comment by nurupo** [comment]
This article needs some updating (well, most of the wiki does). In the end we didn't go through with registering Tox Project as a 501(c)(3) organization in USA. I have removed the bylaws link, don't have time right now to update the article properly though, hopefully I'll remember to do that later.
