### ISSUE TITLE
Black on white text looks bad

### ISSUE THREAD

**Issue by nurupo** [Tox/tox.chat#58]
It looks too think and gray instead of black. It's hard to see. At least harder than the white on gray text.

https://gist.github.com/nurupo/c7e7f454332fcf376315

![eg9yf22](https://cloud.githubusercontent.com/assets/1855294/12528801/051728ce-c171-11e5-8132-6279ce9406e1.png)

**Comment by installgen2** [comment]
Is this no longer an issue now that I have made the text heavier?

**Comment by nurupo** [comment]
Yep, looks better.
