### ISSUE TITLE
Clients page is garbage

### ISSUE THREAD

**Issue by stal888** [Tox/tox.chat#59]
![screen shot 2016-01-22 at 22 57 24](https://cloud.githubusercontent.com/assets/774591/12528931/fdb894ec-c15b-11e5-8f2f-c43f29d4d938.png)

**Comment by installgen2** [comment]
That is simply the nature of \<hr\>'s, they are not full width.

**Comment by ProMcTagonist** [comment]
that's what css is for

**Comment by installgen2** [comment]
I don't see this as being an issue

**Comment by stal888** [comment]
fix it

**Comment by installgen2** [comment]
I'm going to make them even less wide because fuck you

**Comment by stal888** [comment]
thanks :^)

**Comment by RowenStipe** [comment]
The problem lies with the row class that the clients page uses for `<div id="qtox" class="row">`

That class in particular has `margin-right & left` set to -15 px creating the overhang you see.

**Comment by Zer0-One** [comment]
BAM, @RowenStipe to the rescue. 

@installgen2 pls fix
