### ISSUE TITLE
Translation of the web Spanish uncompleted

### ISSUE THREAD

**Issue by dcapeletti** [Tox/tox.chat#65]
Hello, when I show people that tox is, those who speak and read Spanish, I generally share the https://tox.chat/ site but I see that the Spanish translation is incomplete. How do we fix it?

**Comment by installgen2** [comment]
@dcapeletti Despite the misleading name, this is not the right repository, we have abandoned https://tox.chat. Here we are developing a new website, currently seen at http://beta.tox.chat, there is currently __no__ translations for it, and we are waiting on @stal888 merging his new translations engine into this repository, before we can start translating this site.

**Comment by dcapeletti** [comment]
Cool, thanks for the info. While in Spanish, all my friends will know finally what is tox.

**Comment by ProMcTagonist** [comment]
Note that the former beta has now arrived on https://tox.chat and this repository is used for developing it
