### ISSUE TITLE
Add Ricin to clients page ?

### ISSUE THREAD

**Issue by SkyzohKey** [Tox/tox.chat#73]
Hey guys, would it be possible to add Ricin on the clients page ? 

**0.0.2 release:** [here](https://github.com/RicinApp/Ricin/releases) :smile: 
**Screenshot:** http://i.imgur.com/0OIIYvq.png (The current view show a blocked contact)
**Repository:** https://github.com/RicinApp/Ricin
**Maintainer:** [SkyzohKey](https://github.com/SkyzohKey)
**Language:** Vala
**Graphical Toolkit:** GTK+3
**Operating Systems:** Available for Linux (binary) + compilable under Windows/OSX.

**Comment by anoadragon453** [comment]
I don't see why not. Is there a way to link to last successful build? If not, I suppose we could just link to the Github Release page.

**Comment by installgen2** [comment]
Tox may not want some "unsupported" clients on this list, and I'm not entirely sure what the process for approval is. I suppose the most important question is how compliant is your client with the Tox standard? Will add to website once I get approval from someone that knows more.

@Zer0-One @nurupo

**Comment by SkyzohKey** [comment]
Ricin tries to follow the TOX-STS at the maximum I can code. Ricin also participite in making other clients evoluting. (Ie. Markdown support "punch"). I don't see why Ricin couldn't be linked as a non-official client for Tox. But I let you judge if Ricin is nice to appear on the clients page, it would, maybe, permit to find some devs for Ricin, in order to have a futuristic Tox client for Linux ! :)

**Comment by SkyzohKey** [comment]
Just to show you how Ricin try to "futurize" Tox to unleash it's real power :)

https://a.uguu.se/afyslk.webm

**Comment by JFreegman** [comment]
@SkyzohKey The STS has been deprecated by the [TCS](https://www.gitbook.com/book/tox/tox-client-standard/details) now.

**Comment by Zer0-One** [comment]
@SkyzohKey Can you Tox me? 7D07F8E0614A8865B5F24FFC26C07C9916B38415C067CA1388B94B608E1D270549247D230A8B

**Comment by ProMcTagonist** [comment]
@SkyzohKey won't play for me, could you rehost it somewhere more permanent

**Comment by SkyzohKey** [comment]
@JFreegman Yes, i know. When I said STS it's STS + TCS (Tacos :D)
@Zer0-One Yep, added. :)
@ProMcTagonist Here's the video: http://webm.host/c7130/

**Comment by SkyzohKey** [comment]
@Zer0-One @installgen2 @anoadragon453 @JFreegman @ProMcTagonist Bump! Any news ?

**Comment by ProMcTagonist** [comment]
@SkyzohKey thanks for the rehost. Ricin looks nice and seems to be progressing rapidly. Is its markdown compatible with qTox's implementation?

**Comment by anoadragon453** [comment]
@ProMcTagonist @SkyzohKey Ricin's MD implementation is mostly similar, it supports:
```
Bold           -      **text**
Italics         -      _text_
Underline  -      -text-
Strike         -      ~text~
```

qTox's current implementation is:

```
Bold           -      **text**, __text__
Italics         -      *text*. _text_
Underline  -      -text-
Strike         -      ~text~, ~~text~~
```

In addition, qTox avoids some accidental parsing by only accepting syntax characters surrounded by spaces and/or the end or beginning of a chat line. 

qTox also supports three modes of markdown: No Markdown (Plaintext), Markdown with formatting characters shown (Show Formatting Characters), and Markdown without formatting characters (Don't Show Formatting Characters). Showing formatting characters is default to not chance loosing formatting accidentally.

Relevant LOC are:

Ricin: https://github.com/RicinApp/Ricin/blob/master/src/Util.vala#L35

qTox: https://github.com/anoadragon453/qTox/blob/master/src/chatlog/chatmessage.cpp#L189

**Comment by SkyzohKey** [comment]
> In addition, qTox avoids some accidental parsing by only accepting syntax characters surrounded by spaces and/or the end or beginning of a chat line. 

Ricin's also do it using PCRE flags (b/B) ;)
@ProMcTagonist Yep, it should be. I'm waiting the TCS to specify the correct MD tags, then I'll update. :)

**Comment by installgen2** [comment]
Ricin looks pretty fucking awesome holy shit. Truly the best Tox client until Cox finishes expanding and is released.

**Comment by SkyzohKey** [comment]
Wow, thanks. :DDon't forget that I'm not the only one to work on it. @benwaffle @gmscs @Ogromny are also involved :)

**Comment by benwaffle** [comment]
I'm still against the sidepane, and I expect Ricin to support my chosen GTK theme. Also I'm working on many UI improvements so the screenshot will be out of date soon.

**Comment by Zer0-One** [comment]
@installgen2 This raises the issue i brought up before: if we do add Ricin to the clients page right now, how are users supposed to know that Ricin isn't in our apt repo, for example?

**Comment by Zer0-One** [comment]
@installgen2 Should we maybe add a row to the tables listing where a given client is available for download from?

**Comment by ProMcTagonist** [comment]
First party things are on our jenkins and repos. Third party things are not and should be in a separate section.

**Comment by Zer0-One** [comment]
@ProMcTagonist yeah, that's what i'm talking about. Ricin isn't in our apt repo, so a user shouldn't be surprised when they add it and then don't find Ricin.

**Comment by installgen2** [comment]
This website is a mess, lets abandon it and make a new one.

**Comment by anoadragon453** [comment]
Let's toss out this dev team while we're at it.

**Comment by SkyzohKey** [comment]
Since a pull request is open, i close this issue.
https://github.com/Tox/tox.chat/pull/87
