### ISSUE TITLE
Can't download Tox for Ubuntu Trusty

### ISSUE THREAD

**Issue by nurupo** [Tox/tox.chat#84]
It's impossible to get Tox for Ubuntu Trusty following download instructions on [tox.chat](https://tox.chat) website.

The [Binaries wiki page](https://wiki.tox.chat/binaries#debianubuntu) tries to help with that

>To be able to install packages from this repository, run the following in your shell. Be sure to replace “$CODENAME” with the release codename of your distribution (jessie, stretch or sid for Debian and trusty or vivid for Ubuntu). If you use another Debian-based distribution like Ubuntu 14.04 Trusty or Elementary OS, just replace “$CODENAME” by “release”

but not very successfully though. At first it says that you can replace $CODENAME with "trusty", but this doesn't work (see the log below). Then it says to replace $CODENAME with "release" for Trusty. Wtf? Make up your mind!

But the website no longer links to the wiki page, it has a pop-up for Debian/Ubuntu at https://tox.chat/download.html which doesn't mention "release" at all, so users would try to add trusty  with [0 packages](https://pkg.tox.chat/debian/dists/nightly/trusty/binary-amd64/)!

A quick-fix would be to add more complete explanation to the Debian/Ubuntu download popup, saying which Debian/Ubuntu releases are supported and which are not (and/or mention "release"). A proper fix would be to package everything for all supported Debian/Ubuntu releases (@stal @tux3) so that we wouldn't have this issue in the first place.

```
$ cat #tox
<calher> Hi.
<calher> I'm trying to install qTox on an Trusty derivative.
<calher> Since lsb_release -cs spits out something that the repos won't understand, I replaced $(lsb_release -cs) with trusty.
<calher> Everything seemed well when I updated package index.
<calher> qtox failed to install and libtoxcore was not available.
<stal> i don't know if toxcore is actually packaged yet
<stal> ok it actually looks like half the distros have empty package indexes
<calher> I just followed the Ubuntu instructions on tox.chat.
<stal> i guess you could try using "vivid"
<stal> that seems to have packages
<calher> What's vivid?
<stal> as the codename
<calher> Just for completeness's sake, my results are at <http://bluehome.net/~csh/paste/qtox-install-error.txt>.
<stal> yeah so just replace trusty with vivid
<stal> probably won't break your whole system
<calher> stal, what system is vivid?  I'm on Trisquel GNU/Linux, which is based on recent Ubuntu LTS.
<stal> ubuntu 15.04
<nurupo> calher: https://wiki.tox.chat/binaries#debianubuntu
<nurupo> >If you use another Debian-based distribution like Ubuntu 14.04 Trusty or Elementary OS, just replace “$CODENAME” by “release”
<nurupo> despite its name, "release" has actually nothing to do with release versions. in release there are static binaries of nightly builds, which should work on ubuntu 14.04 and others
<calher> Oh, OK.  That sounds like what worked before.
<calher> Cool, it's working.  Thanks, nurupo!
```

**Comment by tux3** [comment]
Trusty is too old and doesn't have some of our dependencies so it's a pain to make proper packages for it. What we could do to simplify the whole process is write a simple installer that checks /etc/issue and pulls the right packages automatically.

**Comment by nurupo** [comment]
>Trusty is too old and doesn't have some of our dependencies so it's a pain to make proper packages for it, hence why "release" should be used instead of "trusty" in this case

Then the instructions on the website should advise to use "release" codename for Ubuntu Trusty.

>What we could do to simplify the whole process is write a simple installer that checks /etc/issue or lsb_release and pulls the right packages automatically, instead of trying to teach the users.

No installers for Linux please, it turns off Linux users greatly, the Qt installer is enough for me :P What we could do is simply add html-spoiler things for each codename, with instructions on how to add Tox package repo, and let the user chose.

**Comment by optimumtact** [comment]
in reality you should not even use release, as the statically compiled binaries are not even guaranteed to work correctly on any given distro's - they were originally just a best effort at supporting people running other repo's. Ideally we would point people towards the community builds instead

https://wiki.tox.chat/community_builds

But yes, this is critical because there are many many packaging bugs on qtox repository where people have a release codename that does not exist.

**Comment by optimumtact** [comment]
Also I can't even edit the wiki page anymore and that's really annoying
