### ISSUE TITLE
FDroid repo without fingerprint & QR code

### ISSUE THREAD

**Issue by rugk** [Tox/tox.chat#99]
You don't list any fingerprint and also no QR code for scanning the FDroid repo. This is not only less secure it is also inconvenient. 

Have a look at the [Guardinproject repo](https://guardianproject.info/fdroid/) to see how it should be done.

**Comment by robinlinden** [comment]
See #128 for the PR fixing this issue. I used the page you suggested as a reference.

**Comment by nurupo** [comment]
Closing the issue as it was fixed by #128.
